import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseTranscript, extractMeta, entriesToMessages, cleanTitle } from '../src/transcript/parser.js';

const text = readFileSync(join(import.meta.dirname, 'fixtures/transcript-basic.jsonl'), 'utf8');

describe('parseTranscript', () => {
  it('skips corrupt lines without throwing', () => {
    expect(parseTranscript(text)).toHaveLength(3);
  });
});

describe('extractMeta', () => {
  it('derives cwd, title, timestamps, count', () => {
    const meta = extractMeta(parseTranscript(text));
    expect(meta.cwd).toBe('/Users/tomin/Projects/slothworks/ergaily');
    expect(meta.title).toBe('Fix the login bug in the auth service please');
    expect(meta.firstAt).toBe(Date.parse('2026-09-01T10:00:00.000Z'));
    expect(meta.lastAt).toBe(Date.parse('2026-09-01T10:01:00.000Z'));
    expect(meta.messageCount).toBe(3);
  });
});

describe('entriesToMessages', () => {
  it('flattens content blocks to chat messages', () => {
    const msgs = entriesToMessages(parseTranscript(text));
    expect(msgs.map((m) => m.role)).toEqual(['user', 'assistant', 'tool_use', 'tool_result']);
    expect(msgs[2]).toMatchObject({ toolName: 'Bash', toolUseId: 't1' });
    expect(msgs[3]).toMatchObject({ toolUseId: 't1', text: '3 passing' });
  });

  it('handles malformed content without throwing', () => {
    const malformed = [
      { type: 'assistant', uuid: 'a9', message: { role: 'assistant', content: null } },
      { type: 'assistant', uuid: 'a10', message: { role: 'assistant' } },
      { type: 'assistant', uuid: 'a11', message: { role: 'assistant', content: 42 } },
    ];
    expect(() => entriesToMessages(malformed as any)).not.toThrow();
    expect(entriesToMessages(malformed as any)).toEqual([]);
  });
});

describe('extractMeta: bare slash commands', () => {
  const userTurn = (uuid: string, at: string, text: string) => ({
    type: 'user',
    uuid,
    timestamp: at,
    cwd: '/Users/tomin/Projects/demo',
    message: { role: 'user', content: text },
  });

  it('skips a leading bare command and titles from the next real turn', () => {
    const meta = extractMeta([
      userTurn('u1', '2026-09-01T10:00:00.000Z', '/clear'),
      userTurn('u2', '2026-09-01T10:00:30.000Z', 'Refactor the billing importer'),
    ] as any);
    expect(meta.title).toBe('Refactor the billing importer');
    // The skipped turn still counts toward the session's message tally/timestamps.
    expect(meta.messageCount).toBe(2);
    expect(meta.firstAt).toBe(Date.parse('2026-09-01T10:00:00.000Z'));
  });

  it('skips a run of bare commands, whatever they are', () => {
    const meta = extractMeta([
      userTurn('u1', '2026-09-01T10:00:00.000Z', '/clear'),
      userTurn('u2', '2026-09-01T10:00:10.000Z', '/login'),
      userTurn('u3', '2026-09-01T10:00:20.000Z', '/superpowers:brainstorming'),
      userTurn('u4', '2026-09-01T10:00:30.000Z', 'Design the tag rules panel'),
    ] as any);
    expect(meta.title).toBe('Design the tag rules panel');
  });

  it('keeps a command that carries arguments — those describe the work', () => {
    const meta = extractMeta([
      userTurn('u1', '2026-09-01T10:00:00.000Z', '/clickup-branch CU-8180'),
      userTurn('u2', '2026-09-01T10:00:30.000Z', 'now write the migration'),
    ] as any);
    expect(meta.title).toBe('/clickup-branch CU-8180');
  });

  it('falls back to the bare command when the session never says anything else', () => {
    const meta = extractMeta([userTurn('u1', '2026-09-01T10:00:00.000Z', '/clear')] as any);
    expect(meta.title).toBe('/clear');
  });
});

describe('extractMeta', () => {
  it('handles malformed content without throwing', () => {
    const malformed = [
      { type: 'user', uuid: 'u1', timestamp: '2026-09-01T10:00:00.000Z', message: { role: 'user', content: null } },
      { type: 'assistant', uuid: 'a1', timestamp: '2026-09-01T10:00:05.000Z', message: { role: 'assistant' } },
    ];
    expect(() => extractMeta(malformed as any)).not.toThrow();
    const meta = extractMeta(malformed as any);
    expect(meta.title).toBe('');
    expect(meta.messageCount).toBe(2);
  });
});

describe('cleanTitle', () => {
  it('passes plain prompts through', () => {
    expect(cleanTitle('Fix the login bug')).toBe('Fix the login bug');
  });

  it('strips caveat blocks, including unclosed ones', () => {
    expect(cleanTitle('<local-command-caveat>Caveat: generated by the user. DO NOT respond</local-command-caveat>')).toBe('');
    expect(cleanTitle('<local-command-caveat>Caveat: truncated, no closing tag')).toBe('');
  });

  it('keeps real text surrounding a noise block', () => {
    expect(cleanTitle('<system-reminder>context stuff</system-reminder>Fix the login bug')).toBe('Fix the login bug');
  });

  it('falls back to the command name and args for slash-command turns', () => {
    const text = '<command-message>clickup-branch</command-message> <command-name>/clickup-branch</command-name> <command-args>https://app.clickup.com/t/1</command-args>';
    expect(cleanTitle(text)).toBe('/clickup-branch https://app.clickup.com/t/1');
    expect(cleanTitle('<command-name>/compact</command-name>')).toBe('/compact');
  });
});

describe('extractMeta noise titles', () => {
  it('skips noise-only first messages and uses the next real prompt', () => {
    const entries = [
      { type: 'user', uuid: 'u1', timestamp: '2026-09-01T10:00:00.000Z', message: { role: 'user', content: '<local-command-caveat>Caveat: generated</local-command-caveat>' } },
      { type: 'user', uuid: 'u2', timestamp: '2026-09-01T10:00:10.000Z', message: { role: 'user', content: 'Real prompt here' } },
    ];
    expect(extractMeta(entries as any).title).toBe('Real prompt here');
  });
});

describe('model extraction', () => {
  const line = (obj: unknown) => JSON.stringify(obj);

  it('extractMeta reports the last assistant model', () => {
    const text = [
      line({ type: 'user', timestamp: '2026-09-16T10:00:00Z', cwd: '/w', message: { role: 'user', content: 'hi' } }),
      line({ type: 'assistant', timestamp: '2026-09-16T10:00:01Z', message: { role: 'assistant', model: 'claude-sonnet-5', content: [{ type: 'text', text: 'a' }] } }),
      line({ type: 'assistant', timestamp: '2026-09-16T10:00:02Z', message: { role: 'assistant', model: 'claude-opus-5', content: [{ type: 'text', text: 'b' }] } }),
    ].join('\n');
    expect(extractMeta(parseTranscript(text)).model).toBe('claude-opus-5');
  });

  it('extractMeta ignores sidechain models', () => {
    const text = [
      line({ type: 'assistant', timestamp: '2026-09-16T10:00:01Z', message: { role: 'assistant', model: 'claude-sonnet-5', content: [{ type: 'text', text: 'a' }] } }),
      line({ type: 'assistant', isSidechain: true, timestamp: '2026-09-16T10:00:02Z', message: { role: 'assistant', model: 'claude-haiku-4-5', content: [{ type: 'text', text: 'sub' }] } }),
    ].join('\n');
    expect(extractMeta(parseTranscript(text)).model).toBe('claude-sonnet-5');
  });

  it('extractMeta reports null when no assistant entry names a model', () => {
    const text = line({ type: 'user', timestamp: '2026-09-16T10:00:00Z', message: { role: 'user', content: 'hi' } });
    expect(extractMeta(parseTranscript(text)).model).toBeNull();
  });

  it('entriesToMessages carries the model on assistant messages only', () => {
    const entries = parseTranscript([
      line({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'hi' } }),
      line({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', model: 'claude-opus-5', content: [{ type: 'text', text: 'yo' }] } }),
    ].join('\n'));
    const messages = entriesToMessages(entries);
    expect(messages[0].model).toBeUndefined();
    expect(messages[1].model).toBe('claude-opus-5');
  });
});
